name: "Publish to GitHub Pages"

env:
  GODOT_VERSION: 4.3

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p bin/web

      - name: Build
        run: godot -v --export-release --headless "Web" bin/web/index.html project.godot

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js bin/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' bin/web/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./bin/web
